- name: Programme de prévention
  slug: programme-de-prevention
  url: https://www.psylio.com/ca/professionals/catherine-laroche?lg=fr
  img:
    src: ../src/images/service_1_480x480.jpeg
    description: Personnes devant éoliennes
  short_description: !markdown |
    Apprendre pour mieux se comprendre
  description: !markdown |
    **Objectif**
    * Améliorer sa compréhension de soi<br />pour éviter de vivre un trouble de<br />santé mentale ou une grande souffrance

    **Durée et modalité**
    * 5 rencontres d'une heure
    * Offert virtuellement en individuel

    **Pour qui**
    * Les adolescents et les adultes

    **Contenus**
    * Discussions et réflexions
    * Outils de réflexion

    **Thèmes abordés**
    * La prévention
    * La compréhension de soi et de l'égo
    * Les masques de l'égo
    * Bagage héréditaire
    * Raison d'être
    * L'équilibre au quotidien

- name: Programmes éducatifs adaptés
  slug: programmes-educatifs-adaptes
  url: https://www.psylio.com/ca/professionals/catherine-laroche?lg=fr
  img:
    src: ../src/images/service_2_240x240.jpeg
    description: Personne qui peint sur le sol
  short_description: !markdown |
    Cibler une problématique spécifique en lien avec la réalité actuelle
  description: !markdown |
    **Objectif général des programmes éducatifs**
    <br />
    Éduquer les clientèles cibles à améliorer leur santé<br />mentale en lien avec leur réalité actuelle. 

    **<u>Programme éducatif : Confidence sur ma dépendance</u>**
    <br />
    **Objectif**
    * Amener les individus à analyser et comprendre leur dépendance. 
    **Durée et modalité**
    * 5 ateliers d'une heure
    * Offert virtuellement en individuel
    * Offert en présentiel pour les groupes
    **Pour qui?**
    * Les gens vivant avec une problématique de dépendance
    **Contenus**
    * Discussions et réflexions
    * Outils de réflexion
    **Thèmes abordés**
    * Profil de consommateur
    * L'égo
    * La communication
    * La gestion des émotions
    * L'estime de soi

    **<u>Programme éducatif : Mon adolescence dans sa transparence</u>**<br/>
    **Objectif**
    * Accompagner les adolescents à mieux comprendre leur identité<br />afin d'être mieux outillé face à leur réalité. 
    **Durée et modalité**
    * 1 rencontre de groupe de 75 minutes
    **Pour qui?**
    * Les adolescents
    **Contenus**
    * Discussions et réflexions
    * Outils de réflexion
    **Thèmes abordés**
    * Les masques de l'égo
    * L'anxiété de performance
    * L'anxiété social
    * Les passions

- name: Accompagnement personnalisé
  slug: accompagnement-personnalise
  url: https://www.psylio.com/ca/professionals/catherine-laroche?lg=fr
  img:
    src: ../src/images/service_3_240x240.jpeg
    description: Personne qui écrit dans un cahier
  short_description: !markdown |
    Désamorcer des comportements nuisibles qui affectent le bien-être au quotidien
  description: !markdown |
    **Objectif**
    * Mise en action d'un plan personnalisé<br />suite à l'identification des comportements<br />nuisibles ciblés par le client dans l'un des<br />programmes.<br /><br />
    * Le plan personnalisé permet d'apprendre<br />de nouvelles façons d'être ou de faire, de<br />modifier des comportements et/ou des<br />habitudes qui peuvent causer un mal-être,<br />afin de retrouver un sentiment de bien-être<br />et de compréhension de soi. 
    <br /><br />
    **Durée et modalité**
    * L'accompagnement est fait en fonction d'un plan personnalisé<br />sur une période 3 mois.
    **Pour qui?**
    * Les adolescents et les adultes
    **Contenus**
    * Discussions et réflexions
    * Outils de réflexion
    * Journal de bord
    **Thèmes abordés**
    * La gestion des émotions
    * La communication
    * L'estime de soi
